name: 'AutoCheck AnyRouter'
description: '自动签到 AnyRouter 服务'
author: 'rakuyo'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  accounts:
    description: 'AnyRouter 账号信息'
    required: true
  # 通知配置
  dingtalk-notif-config:
    description: '钉钉通知配置'
    required: false
  email-notif-config:
    description: '邮件通知配置'
    required: false
  pushplus-notif-config:
    description: 'PushPlus 通知配置'
    required: false
  serverpush-notif-config:
    description: 'Server酱通知配置'
    required: false
  feishu-notif-config:
    description: '飞书通知配置'
    required: false
  wecom-notif-config:
    description: '企业微信通知配置'
    required: false

runs:
  using: 'composite'
  steps:
    - name: 准备环境
      uses: ./.github/actions/prepare-environment

    - name: 执行签到
      uses: ./.github/actions/execute-checkin
      with:
        accounts: ${{ inputs.accounts }}
        dingtalk-notif-config: ${{ inputs.dingtalk-notif-config }}
        email-notif-config: ${{ inputs.email-notif-config }}
        pushplus-notif-config: ${{ inputs.pushplus-notif-config }}
        serverpush-notif-config: ${{ inputs.serverpush-notif-config }}
        feishu-notif-config: ${{ inputs.feishu-notif-config }}
        wecom-notif-config: ${{ inputs.wecom-notif-config }}
