coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: auto
        threshold: 3%
        base: auto
        if_ci_failed: error

    patch:
      default:
        target: 60%
        threshold: 3%
        if_ci_failed: error

comment:
  layout: "diff, flags, files, footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

# 忽略测试文件和配置文件
ignore:
  - "tests/**"
  - "**/__pycache__/**"
  - "**/*.pyc"
  - "**/test_*.py"
  - "**/*_test.py"
  - "setup.py"
  - ".github/**"
  - "htmlcov/**"
  - ".mise.toml"
  - "pyproject.toml"
