[tools]
python = "3.11"

[env]
PYTHONPATH = "./src"
PYTHONIOENCODING = "utf-8"

[tasks]
# 依赖安装
install = "mise exec -- python -m pip install -e ."
install-dev = "mise exec -- python -m pip install -e '.[dev]'"

# Playwright 浏览器安装
install-browsers = "mise exec -- python -m playwright install chromium --with-deps"

# 获取 Playwright 版本
playwright-version = "mise exec -- python -c 'import importlib.metadata; print(importlib.metadata.version(\"playwright\"))'"

# 运行签到脚本（使用 pyproject.toml 中定义的入口点）
checkin = "mise exec -- autocheck-anyrouter"

# 开发环境一键配置
setup = { depends = ["install-dev", "install-browsers"] }

# 测试相关
test = "mise exec -- pytest tests/"
test-cov = "mise exec -- pytest tests/ --cov=src"

# 代码格式化和检查
fmt = "mise exec -- python -m ruff format --preview src tests"
lint = "mise exec -- python -m ruff check src tests"
