name: 'Prepare Checkin Environment'
description: '准备 AnyRouter 签到的运行环境'
author: 'rakuyo'

branding:
  icon: 'package'
  color: 'blue'


outputs:
  cache-hit:
    description: 'Mise 依赖缓存是否命中'
    value: ${{ steps.mise-cache.outputs.cache-hit }}
  playwright-version:
    description: 'Playwright 版本'
    value: ${{ steps.playwright-version.outputs.version }}

runs:
  using: 'composite'
  steps:
    - uses: jdx/mise-action@v3

    - name: 缓存 Mise 依赖
      uses: actions/cache@v4
      id: mise-cache
      with:
        path: |
          ~/.local/share/mise
          ~/.cache/mise
        key: ${{ runner.os }}-mise-${{ hashFiles('pyproject.toml', 'mise.toml') }}
        restore-keys: |
          ${{ runner.os }}-mise-

    - name: 安装依赖
      if: steps.mise-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "缓存未命中，开始安装项目依赖..."
        mise install
        mise run install-dev
        echo "✅ 环境初始化完成"

    - name: 获取 Playwright 版本
      id: playwright-version
      shell: bash
      run: |
        version=$(mise exec -- python -c "import importlib.metadata; print(importlib.metadata.version('playwright'))")
        echo "version=$version" >> $GITHUB_OUTPUT
        echo "Playwright version: $version"

    - name: 缓存 Playwright 浏览器
      uses: actions/cache@v4
      id: playwright-cache
      with:
        path: |
          ~/.cache/ms-playwright
          %LOCALAPPDATA%\ms-playwright
        key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: 安装 Playwright 浏览器
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo "缓存未命中，开始安装 Playwright 浏览器..."
        mise run install-browsers
