name: AnyRouter 自动签到
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    environment: production
    env:
      PYTHONIOENCODING: utf-8
    steps:
    - name: 准备环境
      uses: ./.github/actions/prepare-environment

    - name: 执行签到
      uses: ./.github/actions/execute-checkin
      with:
        accounts: ${{ secrets.ANYROUTER_ACCOUNTS }}
        dingtalk-notif-config: ${{ secrets.DINGTALK_NOTIF_CONFIG }}
        email-notif-config: ${{ secrets.EMAIL_NOTIF_CONFIG }}
        pushplus-notif-config: ${{ secrets.PUSHPLUS_NOTIF_CONFIG }}
        serverpush-notif-config: ${{ secrets.SERVERPUSH_NOTIF_CONFIG }}
        feishu-notif-config: ${{ secrets.FEISHU_NOTIF_CONFIG }}
        wecom-notif-config: ${{ secrets.WECOM_NOTIF_CONFIG }}

