name: AnyRouter 自动签到
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest
    environment: production
    env:
      PYTHONIOENCODING: utf-8
      # 仓库可见性，用于隐私控制
      REPO_VISIBILITY: ${{ github.event.repository.visibility }}
      # 时区设置（可选，默认为 Asia/Shanghai 中国时区）
      TZ: ${{ secrets.TZ }}
      # 时间戳格式（可选，默认为 %Y-%m-%d %H:%M:%S）
      TIMESTAMP_FORMAT: ${{ secrets.TIMESTAMP_FORMAT }}
      # 账号配置
      ANYROUTER_ACCOUNTS: ${{ secrets.ANYROUTER_ACCOUNTS }}
      # 是否显示敏感信息
      SHOW_SENSITIVE_INFO: ${{ secrets.SHOW_SENSITIVE_INFO }}
      # 通知配置
      DINGTALK_NOTIF_CONFIG: ${{ secrets.DINGTALK_NOTIF_CONFIG }}
      EMAIL_NOTIF_CONFIG: ${{ secrets.EMAIL_NOTIF_CONFIG }}
      PUSHPLUS_NOTIF_CONFIG: ${{ secrets.PUSHPLUS_NOTIF_CONFIG }}
      SERVERPUSH_NOTIF_CONFIG: ${{ secrets.SERVERPUSH_NOTIF_CONFIG }}
      FEISHU_NOTIF_CONFIG: ${{ secrets.FEISHU_NOTIF_CONFIG }}
      WECOM_NOTIF_CONFIG: ${{ secrets.WECOM_NOTIF_CONFIG }}
    steps:
      - name: 📥 检出代码
        uses: actions/checkout@v4

      - name: 🔧 安装 Mise
        uses: jdx/mise-action@v3
        with:
          cache_key: "{{default}}-${{ hashFiles('pyproject.toml') }}"

      - name: ⚙️ 安装依赖
        run: mise run install

      - name: 🎭 配置 Playwright 环境
        uses: ./.github/actions/setup-playwright
        id: playwright-setup

      - name: 💾 恢复余额历史缓存
        uses: actions/cache@v4
        with:
          path: balance_hash.txt
          key: balance-hash-${{ github.run_id }}
          restore-keys: |
            balance-hash-

      - name: 🚀 执行签到任务
        run: mise run checkin
